package org.trikkle;

import org.trikkle.annotations.Input;
import org.trikkle.annotations.Output;
import org.trikkle.structs.StrictHashMap;

import java.lang.reflect.Field;
import java.util.*;
import java.util.concurrent.locks.ReentrantLock;

/**
 * A wrapper for a function that can be run by an overseer.
 *
 * @see Input
 * @see Output
 * @since 0.1.0
 */
public abstract class Arc implements Primable {
	private final ReentrantLock lock = new ReentrantLock();
	private final boolean safe;
	private Map<String, Field> inputFields, outputFields;
	private Set<String> inputPointers, outputPointers;
	private String name;
	private ArcStatus status = ArcStatus.IDLE;

	private Overseer overseer;
	private Link link;

	/**
	 * A safe arc is one that cannot be set to a status that is less than its current status. This means it can only be
	 * run once. This is useful for preventing deadlocks and livelocks, as even though arcs cannot directly
	 * ticktock an overseer, it can easily do so indirectly by leveraging nodes and safe arcs.
	 *
	 * @param safe true if this arc is safe
	 */
	public Arc(boolean safe) {
		this.safe = safe;

		List<Field> fields = List.of(getClass().getDeclaredFields());
		if (fields.stream().anyMatch(field ->
				field.isAnnotationPresent(Input.class) || field.isAnnotationPresent(Output.class))) {
			inputFields = new StrictHashMap<>();
			outputFields = new StrictHashMap<>();
			inputPointers = inputFields.keySet();
			outputPointers = outputFields.keySet();
			for (Field field : fields) {
				if (field.isAnnotationPresent(Input.class)) {
					String pointer = field.getAnnotation(Input.class).pointer();
					if (!pointer.isEmpty()) {
						inputFields.put(pointer, field);
					} else {
						inputFields.put(field.getName(), field);
					}
				} else if (field.isAnnotationPresent(Output.class)) {
					String pointer = field.getAnnotation(Output.class).pointer();
					if (!pointer.isEmpty()) {
						outputFields.put(pointer, field);
					} else {
						outputFields.put(field.getName(), field);
					}
				}
			}
		}
	}

	/**
	 * A safe arc is one that cannot be set to a status that is less than its current status. This means it can only be
	 * run once. This is useful for preventing deadlocks and livelocks, as even though arcs cannot directly
	 * ticktock an overseer, it can easily do so indirectly by leveraging nodes and safe arcs.
	 *
	 * @param name the name of this arc
	 * @param safe true if this arc is safe
	 */
	public Arc(String name, boolean safe) {
		this(safe);
		setName(name);
	}

	/**
	 * Override this method to specify what functions to run when this arc is run. This method is called by the overseer
	 * if the link containing this arc is {@link Link#runnable()}.
	 *
	 * @see Link
	 * @see Overseer
	 */
	protected abstract void run(); // lambda won't work because it won't allow for multiple parameter inputs

	void runWrapper() {
		if (inputFields != null) autoFill();
		run();
		if (outputFields != null) autoReturn();
	}

	/**
	 * Gets the datum of the given pointer from the overseer's cache.
	 *
	 * @param pointer the pointer to the datum
	 * @return the datum of the given pointer
	 * @throws NullPointerException if there is no datum with the given pointer in the cache
	 */
	protected Object getDatum(String pointer) {
		if (!overseer.getCache().containsKey(pointer)) {
			throw new NullPointerException("No datum of pointer " + pointer + " is in the cache!");
		}
		return overseer.getCache().get(pointer);
	}

	/**
	 * Returns the datum with the given pointer to the overseer's cache by calling {@link Node#addDatum(String, Object)}.
	 * The datum can be null.
	 *
	 * @param pointer the pointer to the datum
	 * @param datum   the datum to return
	 * @throws NullPointerException     if the pointer is not associated with any node
	 * @throws IllegalArgumentException if the node with this datum is not an output of this arc
	 */
	protected void returnDatum(String pointer, Object datum) {
		Node node = overseer.getNodeOfPointer(pointer);
		if (node == null) {
			throw new NullPointerException("No node is associated with datum " + pointer + "!");
		}

		if (getOutputNodes().contains(node)) {
			node.addDatum(pointer, datum);
		} else {
			throw new IllegalArgumentException(
					"Arc " + this + " cannot return datum " + pointer + " because it is not an output of this arc!");
		}
	}

	/**
	 * Define an alias for an Input or Output's pointer ({@link Input#pointer()}, {@link Output#pointer()}). Use this
	 * when the pointer is dynamic. The Input/Output pointer still has to be unique and may be left empty and
	 * autogenerated from the field name. For example,
	 * <pre>
	 * {@code
	 * new AutoArc() {
	 *  @Input
	 *  String inputStr;
	 *
	 *  {
	 * 	// some function declared outside of this class
	 * 	alias("inputStr", getDynamicPointer());
	 *  }
	 *
	 *  @Override
	 *  void run() {
	 * 	System.out.println(inputStr); // would print getDatum(getDynamicPointer())
	 *  }
	 * }
	 * }
	 * </pre>
	 *
	 * @param pointer the pointer to the Input or Output
	 * @param alias   the alias to use
	 * @see Input
	 * @see Output
	 * @see #getDatum(String)
	 */
	protected void alias(String pointer, String alias) {
		if (inputFields.containsKey(pointer)) {
			inputFields.put(alias, inputFields.remove(pointer));
			return;
		}
		if (outputFields.containsKey(pointer)) {
			outputFields.put(alias, outputFields.remove(pointer));
			return;
		}
		throw new IllegalArgumentException("No Input or Output with pointer " + pointer + " exists!");
	}

	private void autoFill() {
		for (Map.Entry<String, Field> inputEntry : inputFields.entrySet()) {
			String pointer = inputEntry.getKey();
			Field field = inputEntry.getValue();
			Object datum = getDatum(pointer);
			field.setAccessible(true);
			try {
				field.set(this, datum);
			} catch (IllegalAccessException e) {
				throw new RuntimeException(e);
			}
		}
	}

	private void autoReturn() {
		for (Map.Entry<String, Field> outputEntry : outputFields.entrySet()) {
			String pointer = outputEntry.getKey();
			Field field = outputEntry.getValue();
			Object datum;
			field.setAccessible(true);
			try {
				datum = field.get(this);
			} catch (IllegalAccessException e) {
				throw new RuntimeException(e);
			}
			returnDatum(pointer, datum);
		}
	}

	public ArcStatus getStatus() {
		return status;
	}

	/**
	 * Sets the status of the arc. The status cannot be set to null. The status cannot be changed if the arc is already
	 * finished. If the arc is safe, the status cannot be set to a status that is less (see {@link ArcStatus#stage()})
	 * than the current status.
	 *
	 * @param status the new status of the arc
	 * @throws NullPointerException     if the status is null
	 * @throws IllegalStateException    if the arc is already finished
	 * @throws IllegalArgumentException if the arc is safe and the status is less than the current status
	 */
	protected synchronized void setStatus(ArcStatus status) {
		if (status == null) {
			throw new NullPointerException("Status cannot be null!");
		}
		if (status == this.status) return; // no change don't do anything
		if (this.status == ArcStatus.FINISHED) {
			throw new IllegalStateException("Arc " + this + " is already finished!");
		}
		if (safe && status.stage() < this.status.stage()) {
			throw new IllegalArgumentException(
					"Safe arc " + this + " cannot be set to " + status + " from " + this.status + "!");
		}
		this.status = status;
	}

	public String getName() {
		return name;
	}

	/**
	 * Sets the name of this arc. If the name is empty, the name is set to null.
	 *
	 * @param name the new name of this arc
	 */
	public void setName(String name) {
		if (name.isEmpty()) {
			this.name = null;
		} else {
			this.name = name;
		}
	}

	/**
	 * A safe arc is one that cannot be set to a status that is less than its current status. This means it can only be
	 * run once.
	 *
	 * @return true if this arc is safe
	 */
	public boolean isSafe() {
		return safe;
	}

	@Override
	public void primeWith(Overseer overseer) { // aka initialize
		this.overseer = overseer;
		link = overseer.g.arcMap.get(this);
	}

	/**
	 * Gets the input pointers of this arc as declared through {@link Input} and {@link Arc#alias(String, String)},
	 * or manually set (overrides former). If the input pointers are not set, an empty set is returned.
	 *
	 * @return the input pointers of this arc
	 */
	public Set<String> getInputPointers() {
		if (inputPointers == null) {
			return Set.of();
		}
		if (inputFields != null && inputPointers == inputFields.keySet()) {
			return new HashSet<>(inputPointers);
		}
		return inputPointers;
	}

	/**
	 * Sets the input pointers of this arc. All annotations and aliases are overridden.
	 *
	 * @param inputPointers the input pointers of this arc
	 */
	public void setInputPointers(Set<String> inputPointers) {
		this.inputPointers = inputPointers;
		inputFields = null;
	}

	/**
	 * @see #setInputPointers(Set)
	 */
	public void setInputPointers(String... inputPointers) {
		setInputPointers(new HashSet<>(Arrays.asList(inputPointers)));
	}

	/**
	 * Gets the output pointers of this arc as declared through {@link Output} and {@link Arc#alias(String, String)},
	 * or manually set (overrides former). If the output pointers are not set, an empty set is returned.
	 *
	 * @return the output pointers of this arc
	 */
	public Set<String> getOutputPointers() {
		if (outputPointers == null) {
			return Set.of();
		}
		if (outputFields != null && outputPointers == outputFields.keySet()) {
			return new HashSet<>(outputPointers);
		}
		return outputPointers;
	}

	/**
	 * Sets the output pointers of this arc. All annotations and aliases are overridden.
	 *
	 * @param outputPointers the output pointers of this arc
	 */
	public void setOutputPointers(Set<String> outputPointers) {
		this.outputPointers = outputPointers;
		outputFields = null;
	}

	/**
	 * @see #setOutputPointers(Set)
	 */
	public void setOutputPointers(String... outputPointers) {
		setOutputPointers(new HashSet<>(Arrays.asList(outputPointers)));
	}

	/**
	 * Gets the link this arc is a part of. Only available after the arc is primed.
	 *
	 * @return the link this arc is a part of
	 */
	protected Link getLink() {
		return link;
	}

	/**
	 * Gets the dependencies of this arc. Same as {@link Link#getDependencies()}. Only available after the arc is primed.
	 *
	 * @return the dependencies of this arc
	 */
	protected Set<Node> getDependencies() {
		return link.getDependencies();
	}

	/**
	 * Gets the output nodes of this arc. Same as {@link Link#getOutputNodes()}. Only available after the arc is primed.
	 *
	 * @return the output nodes of this arc
	 */
	protected Set<Node> getOutputNodes() {
		return link.getOutputNodes();
	}

	/**
	 * Gets the output node of this arc. Same as {@link Link#getOutputNode()}. Only available after the arc is primed.
	 *
	 * @return the output node of this arc
	 */
	protected Node getOutputNode() {
		return link.getOutputNode();
	}

	protected Overseer getOverseer() {
		return overseer;
	}

	/**
	 * Resets the arc to its initial state. If you declare any persistent fields in an arc, you should override this and
	 * provide a way to reset them.
	 */
	@Override
	public void reset() {
		overseer = null;
		status = ArcStatus.IDLE;
		link = null;
	}

	@Override
	public ReentrantLock getLock() {
		return lock;
	}

	@Override
	public String toString() {
		if (name == null) {
			return super.toString();
		} else {
			return name;
		}
	}
}
